---
#Winning lottery number
winning-number: "4062"

#This section is rewards for winning

##This is the item pool an item will
##be randomly selected from the items
##in the pool and given to the winner
item-id: [
"256"
]
##Damage item does
item-damage: "0"
##Amount of item to give
item-amount: "1"


#This section contains the actual possible numbers for the game
lotto-numbers: [
 "4062","2332","1127","1975",
 "8458","9883","4762","3038",
 "8459","7111","3858","8814"
]

...